version: "3.1"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgres/data/pgdata"
    ports:
      - 5431:5432
    volumes:
      - "./pgdata:/var/lib/postgres/data/pgdata"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
